SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_Tag](
	[TagID] [int] IDENTITY(1,1) NOT NULL,
	[TagName] [nvarchar](250) NOT NULL,
	[TagCount] [int] NOT NULL,
	[TagGroupID] [int] NOT NULL,
	[TagGUID] [uniqueidentifier] NOT NULL,
	[TagCodeName] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_CMS_Tag] PRIMARY KEY NONCLUSTERED 
(
	[TagID] ASC
)
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [IX_CMS_Tag_TagName] ON [dbo].[CMS_Tag]
(
	[TagName] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_CMS_Tag_TagGroupID] ON [dbo].[CMS_Tag]
(
	[TagGroupID] ASC
)
GO
ALTER TABLE [dbo].[CMS_Tag] ADD  CONSTRAINT [DEFAULT_CMS_Tag_TagGUID]  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [TagGUID]
GO
ALTER TABLE [dbo].[CMS_Tag] ADD  CONSTRAINT [DEFAULT_CMS_Tag_TagCodeName]  DEFAULT (N'') FOR [TagCodeName]
GO
ALTER TABLE [dbo].[CMS_Tag]  WITH CHECK ADD  CONSTRAINT [FK_CMS_Tag_TagGroupID_CMS_TagGroup] FOREIGN KEY([TagGroupID])
REFERENCES [dbo].[CMS_TagGroup] ([TagGroupID])
GO
ALTER TABLE [dbo].[CMS_Tag] CHECK CONSTRAINT [FK_CMS_Tag_TagGroupID_CMS_TagGroup]
GO
