SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_ACL](
	[ACLID] [int] IDENTITY(1,1) NOT NULL,
	[ACLInheritedACLs] [nvarchar](450) NOT NULL,
	[ACLGUID] [uniqueidentifier] NOT NULL,
	[ACLLastModified] [datetime2](7) NOT NULL,
	[ACLSiteID] [int] NULL,
 CONSTRAINT [PK_CMS_ACL] PRIMARY KEY CLUSTERED 
(
	[ACLID] ASC
)
)

GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_CMS_ACL_ACLInheritedACLs] ON [dbo].[CMS_ACL]
(
	[ACLInheritedACLs] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_CMS_ACL_ACLSiteID] ON [dbo].[CMS_ACL]
(
	[ACLSiteID] ASC
)
GO
ALTER TABLE [dbo].[CMS_ACL] ADD  CONSTRAINT [DF__CMS_ACL__ACLInhe__060DEAE8]  DEFAULT ('') FOR [ACLInheritedACLs]
GO
ALTER TABLE [dbo].[CMS_ACL] ADD  CONSTRAINT [DEFAULT_CMS_ACL_ACLGUID]  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [ACLGUID]
GO
ALTER TABLE [dbo].[CMS_ACL] ADD  CONSTRAINT [DEFAULT_CMS_ACL_ACLLastModified]  DEFAULT ('10/30/2008 9:17:31 AM') FOR [ACLLastModified]
GO
ALTER TABLE [dbo].[CMS_ACL]  WITH CHECK ADD  CONSTRAINT [FK_CMS_ACL_ACLSiteID_CMS_Site] FOREIGN KEY([ACLSiteID])
REFERENCES [dbo].[CMS_Site] ([SiteID])
GO
ALTER TABLE [dbo].[CMS_ACL] CHECK CONSTRAINT [FK_CMS_ACL_ACLSiteID_CMS_Site]
GO
