SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_ACLItem](
	[ACLItemID] [int] IDENTITY(1,1) NOT NULL,
	[ACLID] [int] NOT NULL,
	[UserID] [int] NULL,
	[RoleID] [int] NULL,
	[Allowed] [int] NOT NULL,
	[Denied] [int] NOT NULL,
	[LastModified] [datetime2](7) NOT NULL,
	[LastModifiedByUserID] [int] NULL,
	[ACLItemGUID] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_CMS_ACLItem] PRIMARY KEY CLUSTERED 
(
	[ACLItemID] ASC
)
)

GO
CREATE NONCLUSTERED INDEX [IX_CMS_ACLItem_ACLID] ON [dbo].[CMS_ACLItem]
(
	[ACLID] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_CMS_ACLItem_LastModifiedByUserID] ON [dbo].[CMS_ACLItem]
(
	[LastModifiedByUserID] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_CMS_ACLItem_RoleID] ON [dbo].[CMS_ACLItem]
(
	[RoleID] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_CMS_ACLItem_UserID] ON [dbo].[CMS_ACLItem]
(
	[UserID] ASC
)
GO
ALTER TABLE [dbo].[CMS_ACLItem] ADD  CONSTRAINT [DF__CMS_ACLIt__Allow__0EA330E9]  DEFAULT ((0)) FOR [Allowed]
GO
ALTER TABLE [dbo].[CMS_ACLItem] ADD  CONSTRAINT [DF__CMS_ACLIt__Denie__0F975522]  DEFAULT ((0)) FOR [Denied]
GO
ALTER TABLE [dbo].[CMS_ACLItem] ADD  CONSTRAINT [DEFAULT_CMS_ACLItem_ACLItemGUID]  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [ACLItemGUID]
GO
ALTER TABLE [dbo].[CMS_ACLItem]  WITH CHECK ADD  CONSTRAINT [FK_CMS_ACLItem_ACLID_CMS_ACL] FOREIGN KEY([ACLID])
REFERENCES [dbo].[CMS_ACL] ([ACLID])
GO
ALTER TABLE [dbo].[CMS_ACLItem] CHECK CONSTRAINT [FK_CMS_ACLItem_ACLID_CMS_ACL]
GO
ALTER TABLE [dbo].[CMS_ACLItem]  WITH CHECK ADD  CONSTRAINT [FK_CMS_ACLItem_LastModifiedByUserID_CMS_User] FOREIGN KEY([LastModifiedByUserID])
REFERENCES [dbo].[CMS_User] ([UserID])
GO
ALTER TABLE [dbo].[CMS_ACLItem] CHECK CONSTRAINT [FK_CMS_ACLItem_LastModifiedByUserID_CMS_User]
GO
ALTER TABLE [dbo].[CMS_ACLItem]  WITH CHECK ADD  CONSTRAINT [FK_CMS_ACLItem_RoleID_CMS_Role] FOREIGN KEY([RoleID])
REFERENCES [dbo].[CMS_Role] ([RoleID])
GO
ALTER TABLE [dbo].[CMS_ACLItem] CHECK CONSTRAINT [FK_CMS_ACLItem_RoleID_CMS_Role]
GO
ALTER TABLE [dbo].[CMS_ACLItem]  WITH CHECK ADD  CONSTRAINT [FK_CMS_ACLItem_UserID_CMS_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[CMS_User] ([UserID])
GO
ALTER TABLE [dbo].[CMS_ACLItem] CHECK CONSTRAINT [FK_CMS_ACLItem_UserID_CMS_User]
GO
