SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_SMTPServerSite](
	[ServerID] [int] NOT NULL,
	[SiteID] [int] NOT NULL,
 CONSTRAINT [PK_CMS_SMTPServerSite] PRIMARY KEY CLUSTERED 
(
	[ServerID] ASC,
	[SiteID] ASC
)
)

GO
CREATE NONCLUSTERED INDEX [IX_CMS_SMTPServerSite_SiteID] ON [dbo].[CMS_SMTPServerSite]
(
	[SiteID] ASC
)
GO
ALTER TABLE [dbo].[CMS_SMTPServerSite]  WITH CHECK ADD  CONSTRAINT [FK_CMS_SMTPServerSite_CMS_Site] FOREIGN KEY([SiteID])
REFERENCES [dbo].[CMS_Site] ([SiteID])
GO
ALTER TABLE [dbo].[CMS_SMTPServerSite] CHECK CONSTRAINT [FK_CMS_SMTPServerSite_CMS_Site]
GO
ALTER TABLE [dbo].[CMS_SMTPServerSite]  WITH CHECK ADD  CONSTRAINT [FK_CMS_SMTPServerSite_CMS_SMTPServer] FOREIGN KEY([ServerID])
REFERENCES [dbo].[CMS_SMTPServer] ([ServerID])
GO
ALTER TABLE [dbo].[CMS_SMTPServerSite] CHECK CONSTRAINT [FK_CMS_SMTPServerSite_CMS_SMTPServer]
GO
