SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_FormRole](
	[FormID] [int] NOT NULL,
	[RoleID] [int] NOT NULL,
 CONSTRAINT [PK_CMS_FormRole] PRIMARY KEY CLUSTERED 
(
	[FormID] ASC,
	[RoleID] ASC
)
)

GO
CREATE NONCLUSTERED INDEX [IX_CMS_FormRole_RoleID] ON [dbo].[CMS_FormRole]
(
	[RoleID] ASC
)
GO
ALTER TABLE [dbo].[CMS_FormRole]  WITH CHECK ADD  CONSTRAINT [FK_CMS_FormRole_FormID_CMS_Form] FOREIGN KEY([FormID])
REFERENCES [dbo].[CMS_Form] ([FormID])
GO
ALTER TABLE [dbo].[CMS_FormRole] CHECK CONSTRAINT [FK_CMS_FormRole_FormID_CMS_Form]
GO
ALTER TABLE [dbo].[CMS_FormRole]  WITH CHECK ADD  CONSTRAINT [FK_CMS_FormRole_RoleID_CMS_Role] FOREIGN KEY([RoleID])
REFERENCES [dbo].[CMS_Role] ([RoleID])
GO
ALTER TABLE [dbo].[CMS_FormRole] CHECK CONSTRAINT [FK_CMS_FormRole_RoleID_CMS_Role]
GO
