SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_ClassSite](
	[ClassID] [int] NOT NULL,
	[SiteID] [int] NOT NULL,
 CONSTRAINT [PK_CMS_ClassSite] PRIMARY KEY CLUSTERED 
(
	[ClassID] ASC,
	[SiteID] ASC
)
)

GO
CREATE NONCLUSTERED INDEX [IX_CMS_ClassSite_SiteID] ON [dbo].[CMS_ClassSite]
(
	[SiteID] ASC
)
GO
ALTER TABLE [dbo].[CMS_ClassSite]  WITH CHECK ADD  CONSTRAINT [FK_CMS_Class_ClassID_CMS_Class] FOREIGN KEY([ClassID])
REFERENCES [dbo].[CMS_Class] ([ClassID])
GO
ALTER TABLE [dbo].[CMS_ClassSite] CHECK CONSTRAINT [FK_CMS_Class_ClassID_CMS_Class]
GO
ALTER TABLE [dbo].[CMS_ClassSite]  WITH CHECK ADD  CONSTRAINT [FK_CMS_Class_SiteID_CMS_Site] FOREIGN KEY([SiteID])
REFERENCES [dbo].[CMS_Site] ([SiteID])
GO
ALTER TABLE [dbo].[CMS_ClassSite] CHECK CONSTRAINT [FK_CMS_Class_SiteID_CMS_Site]
GO
