SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMS_OpenIDUser](
	[OpenIDUserID] [int] IDENTITY(1,1) NOT NULL,
	[OpenID] [nvarchar](450) NOT NULL,
	[OpenIDProviderURL] [nvarchar](450) NULL,
	[UserID] [int] NOT NULL,
 CONSTRAINT [PK_CMS_OpenIDUser] PRIMARY KEY CLUSTERED 
(
	[OpenIDUserID] ASC
)
)

GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_CMS_OpenIDUser_OpenID] ON [dbo].[CMS_OpenIDUser]
(
	[OpenID] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_CMS_OpenIDUser_UserID] ON [dbo].[CMS_OpenIDUser]
(
	[UserID] ASC
)
GO
ALTER TABLE [dbo].[CMS_OpenIDUser] ADD  CONSTRAINT [DEFAULT_cms_OpenIDUser_OpenID]  DEFAULT ('') FOR [OpenID]
GO
ALTER TABLE [dbo].[CMS_OpenIDUser] ADD  CONSTRAINT [DEFAULT_cms_OpenIDUser_UserID]  DEFAULT ((0)) FOR [UserID]
GO
ALTER TABLE [dbo].[CMS_OpenIDUser]  WITH CHECK ADD  CONSTRAINT [FK_CMS_OpenIDUser_UserID_CMS_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[CMS_User] ([UserID])
GO
ALTER TABLE [dbo].[CMS_OpenIDUser] CHECK CONSTRAINT [FK_CMS_OpenIDUser_UserID_CMS_User]
GO
