SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COM_SKUTaxClasses](
	[SKUID] [int] NOT NULL,
	[TaxClassID] [int] NOT NULL,
 CONSTRAINT [PK_COM_SKUTaxClasses] PRIMARY KEY CLUSTERED 
(
	[SKUID] ASC,
	[TaxClassID] ASC
)
)

GO
CREATE NONCLUSTERED INDEX [IX_COM_SKUTaxClasses_TaxClassID] ON [dbo].[COM_SKUTaxClasses]
(
	[TaxClassID] ASC
)
GO
ALTER TABLE [dbo].[COM_SKUTaxClasses]  WITH CHECK ADD  CONSTRAINT [FK_COM_SKUTaxClasses_SKUID_COM_SKU] FOREIGN KEY([SKUID])
REFERENCES [dbo].[COM_SKU] ([SKUID])
GO
ALTER TABLE [dbo].[COM_SKUTaxClasses] CHECK CONSTRAINT [FK_COM_SKUTaxClasses_SKUID_COM_SKU]
GO
ALTER TABLE [dbo].[COM_SKUTaxClasses]  WITH CHECK ADD  CONSTRAINT [FK_COM_SKUTaxClasses_TaxClassID_COM_TaxClass] FOREIGN KEY([TaxClassID])
REFERENCES [dbo].[COM_TaxClass] ([TaxClassID])
GO
ALTER TABLE [dbo].[COM_SKUTaxClasses] CHECK CONSTRAINT [FK_COM_SKUTaxClasses_TaxClassID_COM_TaxClass]
GO
