SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COM_Bundle](
	[BundleID] [int] NOT NULL,
	[SKUID] [int] NOT NULL,
 CONSTRAINT [PK_COM_Bundle] PRIMARY KEY CLUSTERED 
(
	[BundleID] ASC,
	[SKUID] ASC
)
)

GO
CREATE NONCLUSTERED INDEX [IX_COM_Bundle_SKUID] ON [dbo].[COM_Bundle]
(
	[SKUID] ASC
)
GO
ALTER TABLE [dbo].[COM_Bundle]  WITH CHECK ADD  CONSTRAINT [FK_COM_Bundle_BundleID_COM_SKU] FOREIGN KEY([BundleID])
REFERENCES [dbo].[COM_SKU] ([SKUID])
GO
ALTER TABLE [dbo].[COM_Bundle] CHECK CONSTRAINT [FK_COM_Bundle_BundleID_COM_SKU]
GO
ALTER TABLE [dbo].[COM_Bundle]  WITH CHECK ADD  CONSTRAINT [FK_COM_Bundle_SKUID_COM_SKU] FOREIGN KEY([SKUID])
REFERENCES [dbo].[COM_SKU] ([SKUID])
GO
ALTER TABLE [dbo].[COM_Bundle] CHECK CONSTRAINT [FK_COM_Bundle_SKUID_COM_SKU]
GO
