SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COM_Wishlist](
	[UserID] [int] NOT NULL,
	[SKUID] [int] NOT NULL,
	[SiteID] [int] NOT NULL,
 CONSTRAINT [PK_COM_Wishlist] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[SKUID] ASC,
	[SiteID] ASC
)
)

GO
CREATE NONCLUSTERED INDEX [IX_COM_Wishlist_SiteID] ON [dbo].[COM_Wishlist]
(
	[SiteID] ASC
)
GO
CREATE NONCLUSTERED INDEX [IX_COM_Wishlist_SKUID] ON [dbo].[COM_Wishlist]
(
	[SKUID] ASC
)
GO
ALTER TABLE [dbo].[COM_Wishlist]  WITH CHECK ADD  CONSTRAINT [FK_COM_Wishlist_SiteID_CMS_Site] FOREIGN KEY([SiteID])
REFERENCES [dbo].[CMS_Site] ([SiteID])
GO
ALTER TABLE [dbo].[COM_Wishlist] CHECK CONSTRAINT [FK_COM_Wishlist_SiteID_CMS_Site]
GO
ALTER TABLE [dbo].[COM_Wishlist]  WITH CHECK ADD  CONSTRAINT [FK_COM_Wishlist_SKUID_COM_SKU] FOREIGN KEY([SKUID])
REFERENCES [dbo].[COM_SKU] ([SKUID])
GO
ALTER TABLE [dbo].[COM_Wishlist] CHECK CONSTRAINT [FK_COM_Wishlist_SKUID_COM_SKU]
GO
ALTER TABLE [dbo].[COM_Wishlist]  WITH CHECK ADD  CONSTRAINT [FK_COM_Wishlist_UserID_CMS_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[CMS_User] ([UserID])
GO
ALTER TABLE [dbo].[COM_Wishlist] CHECK CONSTRAINT [FK_COM_Wishlist_UserID_CMS_User]
GO
