SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COM_SKUAllowedOption](
	[OptionSKUID] [int] NOT NULL,
	[SKUID] [int] NOT NULL,
 CONSTRAINT [PK_COM_SKUOption] PRIMARY KEY CLUSTERED 
(
	[OptionSKUID] ASC,
	[SKUID] ASC
)
)

GO
CREATE NONCLUSTERED INDEX [IX_COM_SKUAllowedOption_SKUID] ON [dbo].[COM_SKUAllowedOption]
(
	[SKUID] ASC
)
GO
ALTER TABLE [dbo].[COM_SKUAllowedOption]  WITH CHECK ADD  CONSTRAINT [FK_COM_SKUOption_OptionSKUID_COM_SKU] FOREIGN KEY([OptionSKUID])
REFERENCES [dbo].[COM_SKU] ([SKUID])
GO
ALTER TABLE [dbo].[COM_SKUAllowedOption] CHECK CONSTRAINT [FK_COM_SKUOption_OptionSKUID_COM_SKU]
GO
ALTER TABLE [dbo].[COM_SKUAllowedOption]  WITH CHECK ADD  CONSTRAINT [FK_COM_SKUOption_SKUID_COM_SKU] FOREIGN KEY([SKUID])
REFERENCES [dbo].[COM_SKU] ([SKUID])
GO
ALTER TABLE [dbo].[COM_SKUAllowedOption] CHECK CONSTRAINT [FK_COM_SKUOption_SKUID_COM_SKU]
GO
