SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[Proc_CMS_ACL_ClearACLs]
	@NodeID int, @NewACLID int
AS
BEGIN
	DECLARE @OldNodeACLID int;
	SET @OldNodeACLID = (SELECT NodeACLID FROM CMS_Tree WHERE NodeID = @NodeID AND CMS_Tree.NodeIsACLOwner = 1)

	UPDATE CMS_Tree SET NodeACLID = @NewACLID WHERE NodeIsACLOwner = 1 AND NodeID = @NodeID
	DELETE FROM CMS_ACLItem WHERE ACLID IN (SELECT ACLID FROM CMS_ACL WHERE ACLID = @OldNodeACLID)
    DELETE FROM CMS_ACL WHERE ACLID = @OldNodeACLID
END


GO
